[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_mint = "BH4PdDrrKvnrisdxmdTftf8rxPzmwN74jbXmKanSDhyo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/andrej/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test.validator]
url = "https://api.mainnet-beta.solana.com"
[test]
startup_wait = 20000
[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
